# Generated by Django 5.2.3 on 2025-07-02 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="joboffer",
            name="country",
        ),
        migrations.RemoveField(
            model_name="joboffer",
            name="daily_salary_eur",
        ),
        migrations.RemoveField(
            model_name="joboffer",
            name="skill",
        ),
        migrations.AddField(
            model_name="joboffer",
            name="date_posted",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
