# Generated by Django 5.2.3 on 2025-07-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_remove_joboffer_country_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalaryByCountry",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("normalized_title", models.TextField(null=True)),
                ("country", models.TextField(null=True)),
                ("salary_min", models.FloatField(null=True)),
                ("salary_max", models.FloatField(null=True)),
                ("salary_median", models.FloatField(null=True)),
                ("date", models.DateField(null=True)),
                ("currency", models.CharField(max_length=10, null=True)),
            ],
            options={
                "db_table": "salary_by_country",
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="joboffer",
            options={"managed": False},
        ),
    ]
